workflows:
  android-release:
    name: LodeLynk Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.lodelynk.base"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/**/*.aab
